kasse/urls.py
from django.urls import path
from .views import *
from . import ajax_views

urlpatterns = [
    path('', kasse_view, name="kasse"),
    path('<int:menu_id>', menu_view, name='single_menu'),

    path('tableset/<int:table_set_id>', tableset_view, name="tableset"),
    path('tableset/<int:table_set_id>/<int:table_id>', table_menu_view, name="table_menu"),
    path('tableset/<int:table_set_id>/<int:table_id>/addProduct', add_product_to_table_view, name="add_product_to_table"),
    path('tableset/<int:table_set_id>/<int:table_id>/removeProduct', remove_product_from_table_view, name='remove_product_from_table'),
    path('tableset/<int:table_set_id>/<int:table_id>/book', book_table_view, name='book_table'),

    path('settings', settings_view, name="settings"),
    path('settings/<int:menu_id>', menu_edit_view, name="edit_menu"),
    path('settings/<int:menu_id>/delete', menu_delete_view, name="delete_menu"),

    path('settings/menus/add', add_menu_view, name="add_menu"),

    path('settings/table_sets/<int:table_set_id>', table_set_edit_view, name="edit_table_set"),
    path('settings/table_sets/<int:table_set_id>/edit', table_set_data_edit_view, name="edit_table_set_data"),
    path('settings/table_sets/<int:table_set_id>/delete', table_set_delete_view, name="delete_table_set"),
    path('settings/table_sets/add', add_table_set_view, name="add_table_set"),

    path('settings/products', product_list_view, name="product_list"),
    path('settings/products/add', add_product_view, name="add_product"),
    path('settings/products/<int:product_id>/edit', edit_product_view, name="edit_product"),
    path('settings/products/<int:product_id>/delete', remove_product, name="delete_product"),

    path('settings/productCategories/add', add_product_category_view, name="add_product_category"),
    path('settings/productCategories/<int:product_category_id>/edit', edit_product_category_view, name="edit_product_category"),
    path('settings/productCategories/<int:product_category_id>/remove', delete_product_category_view, name="remove_product_category"),

    path('settings/events', events_view, name="events"),
    path('settings/events/create', create_event_view, name="create_event"),
    path('settings/events/<int:event_id>', event_view, name="event"),
    path('settings/events/<int:event_id>/edit', edit_event_view, name="edit_event"),
    path('settings/events/<int:event_id>/remove', delete_event_view, name="remove_event"),
    path('settings/events/<int:event_id>/stats', event_stats_view, name="event_stats"),

    path('settings/users', users_view, name="users"),
    path('settings/users/create', add_user_view, name="add_user"),
    path('settings/users/<int:user_id>/set_password', set_password_view, name="set_password"),
    path('settings/users/<int:user_id>/remove', remove_user_view, name="remove_user"),

    path('settings/general_settings', general_settings_view, name="general_settings"),

    path('ajax/settings/menus/<int:menu_id>/remove_product', ajax_views.update_menu_view, name="ajax_update_menu"),
    path('ajax/settings/tablesets/<int:tableset_id>/update', ajax_views.update_tableset_view, name="ajax_update_tableset"),
    path('ajax/searchProducts', ajax_views.search_products, name="search_products"),
    path('ajax/add_sale', ajax_views.add_sale_view, name="add_sale"),
    path('ajax/open_drawer', ajax_views.open_drawer, name="open_drawer"),
    path('ajax/time', ajax_views.time_view, name="time"),

]

kassensystem/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from kasse import urls as kasse_urls

urlpatterns = [
    path('login', auth_views.LoginView.as_view(), name="login"),
    path('logout', auth_views.LogoutView.as_view(), name="logout"),
    path('', include(('kasse.urls', 'kasse'), namespace='kasse'))
]

kasse/models.py
from django.db import models
from djmoney.models.fields import MoneyField
import json

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField('Name', max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField('Name', max_length=50)
    category = models.ForeignKey(to=ProductCategory, on_delete=models.SET_DEFAULT, related_name='products',
                                 blank=True, default=None, null=True)
    price = MoneyField('Preis', decimal_places=2, max_digits=20, default_currency='EUR')


class Menu(models.Model):
    name = models.CharField('Name', max_length=50)
    products = models.ManyToManyField(Product, through='MenuItem')

    def sort_products(self):
        return self.products.order_by('menuitem__sort')

    def __str__(self):
        return self.name


class MenuItem(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    sort = models.IntegerField()
    color = models.CharField(max_length=50, default='default')


class AccountEntry(models.Model):
    types = (
        ('sale', 'Verkauf'),
        ('output', 'Entnahme'),
        ('input', 'Einzahlung')
    )
    type = models.CharField('Typ', choices=types, max_length=20)
    comment = models.TextField('Kommentar')
    amount = MoneyField('Betrag', max_digits=20, decimal_places=2, default_currency='EUR')
    timestamp = models.DateTimeField(auto_now=True)
    user = models.CharField('Benutzer', max_length=200, default='')


class Event(models.Model):
    name = models.CharField('Name', max_length=300)
    start = models.DateTimeField('Start')
    end = models.DateTimeField('Ende')


class TableSet(models.Model):
    name = models.CharField('Name', max_length=300)
    menu = models.ForeignKey(Menu, on_delete=models.PROTECT, verbose_name='Menü')


class Table(models.Model):
    name = models.CharField('Name', max_length=300)
    table_set = models.ForeignKey(TableSet, on_delete=models.CASCADE)
    pos_x = models.FloatField()
    pos_y = models.FloatField()
    size_x = models.FloatField()
    size_y = models.FloatField()
    bookings = models.TextField(blank=True)

    def total(self):
        total = 0.0
        if self.bookings != "":
            bookings = json.loads(self.bookings)
            for booking in bookings:
                total += booking.get('price', 0.0)
        return total

templates/settings/checkout_list.html
{% extends 'settings/base.html' %}

{% block settings_content %}
    {% for menu in menus %}
        <a href="{% url 'kasse:edit_menu' menu.id %}"><button class="btn btn-default btn-menu">{{ menu.name }}</button></a>
    {% endfor %}

    <a href="{% url 'kasse:add_menu' %}"><button class="btn btn-primary btn-menu">Menü hinzufügen</button></a>
    <hr>
    {% for table_set in table_sets %}
        <a href="{% url 'kasse:edit_table_set' table_set.id %}"><button class="btn btn-default btn-menu">{{ table_set.name }}</button></a>
    {% endfor %}

    <a href="{% url 'kasse:add_table_set' %}"><button class="btn btn-info btn-menu">Tisch- anordnung hinzufügen</button></a>
{% endblock %}

templates/settings/create_user_form.html
{% extends 'settings/base.html' %}

{% block settings_content %}
    <h1>Benutzer erstellen</h1>
    <form action="" method="post" class="form-horizontal">
        {% include 'form.html' %}
        <button type="submit" class="btn btn-primary">Speichern</button>
    </form>
{% endblock %}

templates/settings/event.html
{% extends 'settings/base.html' %}

{% block settings_content %}
    <h1>Eventübersicht <small>{{ event.name }}</small></h1>
    <table class="table tabel-condensed table-striped table-hover">
    <thead>
    <tr>
        <th>Typ</th>
        <th>Zeit</th>
        <th style="text-align: right;">Betrag</th>
    </tr>
    </thead>
    <tbody>
    {% for entry in entries %}
        <tr>
            <td>{{ entry.get_type_display }}</td>
            <td>{{ entry.timestamp }}</td>
            <td style="text-align: right;">{{ entry.amount }}</td>
        </tr>
    {% endfor %}
    </tbody>
    <tfoot>
    <tr>
        <td colspan="2" style="text-align: right;"><b>Summe</b></td>
        <td style="text-align: right;"><b>{{ complete_sum }}</b></td>
    </tr>
    </tfoot>
    </table>
{% endblock %}

templates/settings/event_form.html
{% extends 'settings/base.html' %}

{% block settings_content %}
    <h1>{{ title }}</h1>
    <form action="" method="post" class="form-horizontal">
    {% include 'form.html' %}
    <button class="btn btn-primary">Speichern</button>
    </form>
    <script type="application/javascript">
    $(function () {
        $('#{{ form.start.auto_id }}').datetimepicker({
            format: 'DD.MM.YYYY HH:mm'
        });
        $('#{{ form.end.auto_id }}').datetimepicker({
            format: 'DD.MM.YYYY HH:mm',
            useCurrent: false //Important! See issue #1075
        });
        $("#{{ form.start.auto_id }}").on("dp.change", function (e) {
            $('#{{ form.end.auto_id }}').data("DateTimePicker").minDate(e.date);
        });
        $("#{{ form.end.auto_id }}").on("dp.change", function (e) {
            $('#{{ form.start.auto_id }}').data("DateTimePicker").maxDate(e.date);
        });
    })
    </script>
{% endblock %}

templates/settings/events.html
{% extends 'settings/base.html' %}

{% block settings_content %}
    <h1>Events</h1>
    <a href="{% url 'kasse:create_event' %}" class="btn btn-primary">Event erstellen</a>
    <table class="table table-striped table-hover">
    <thead>
    <tr>
        <th>Name</th>
        <th>Start</th>
        <th>Ende</th>
        <th style="text-align: right;">Aktionen</th>
    </tr>
    </thead>
    <tbody>
    {% for event in events %}
        <tr>
            <td><a href="{% url 'kasse:event' event.id %}">{{ event.name }}</a></td>
        <td>{{ event.start }}</td>
        <td>{{ event.end }}</td>
        <td style="text-align: right;">
            <a href="{% url 'kasse:event_stats' event.id %}" class="btn btn-default btn-xs"><i class="fa fa-chart-bar"></i></a>
            <a href="{% url 'kasse:edit_event' event.id %}" class="btn btn-default btn-xs"><i class="glyphicon glyphicon-edit"></i></a>
            <a href="#" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#event{{ event.id }}_delete_modal"><i class="glyphicon glyphicon-trash"></i></a>
            <div class="modal fade" id="event{{ event.id }}_delete_modal" tabindex="-1" role="dialog" aria-labelledby="event{{ event.id }}_delete_model_label" style="text-align: left;">
                <form action="{% url 'kasse:remove_event' event.id %}" method="post">
                    {% csrf_token %}
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title" id="event{{ event.id }}_delete_model_label">Event entfernen</h4>
                            </div>
                            <div class="modal-body">
                                Soll das Event "{{ event.name }}" wirklich entfernt werden?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Abbrechen</button>
                                <button type="submit" class="btn btn-danger">Entfernen</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </td>
        </tr>
    {% endfor %}
    {% if not events %}
        <tr><td colspan="100" style="text-align: center;">Es wurden bisher keine Events angelegt.</td></tr>
    {% endif %}
    </tbody>
    </table>
{% endblock %}

templates/settings/menu_form.html
{% extends 'settings/base.html' %}

{% block settings_content %}
    <h1>Menü {% if edit %}bearbeiten{% else %}erstellen{% endif %}</h1>
    <br>
    <form action="{{ request.path }}" method="post" class="form-horizontal">
    {% for field in form %}
        {% include 'form.html' with form=form %}
    {% endfor %}
    <button class="btn btn-primary">Speichern</button>
    </form>
{% endblock %}

templates/settings/menu_settings.html
{% extends 'settings/base.html' %}
{% load djmoney %}

{% block settings_content %}
    <div class="alert alert-success pull-right" role="alert" id="saved-alert" style="display: none;"><b>Erfolgreich gespeichert!</b></div>
    <h1>
        {{ menu.name }}
        <div class="btn-group">
            <button class="btn btn-danger" data-toggle="modal" data-target="#menu{{ menu.id }}_delete_modal">Menu entfernen</button>
            <button class="btn btn-primary" onclick="save()">Speichern</button>
        </div>
    </h1>
    <br>
    <div class="col-sm-8 col-lg-9 menu-container" id="menu-container" style="overflow-y: scroll;">{% for menuitem in menu.menuitem_set.all %}<button class="btn btn-{{ menuitem.color }} btn-menu menu-item" data-product-id="{{ menuitem.product.id }}" data-color="{{ menuitem.color }}">{{ menuitem.product.name }}<br><b>{{ menuitem.product.price }}</b></button>{% endfor %}<button class="btn btn-menu btn-add" id="add-button" style="display: none;"></button></div>
    <div class="col-sm-4 col-lg-3 products-container">
        <form action="" class="form-horizontal">
            <div class="form-group">
                <div class="input-group">
                    <input type="text" class="form-control" id="product-search-field" placeholder="Suche...">
                    <div class="btn input-group-addon"><i class="glyphicon glyphicon-search"></i></div>
                </div>
            </div>
        </form>
        <div id="product-search-results">
        {% for product in all_products %}<button class="btn btn-default btn-menu palette-product" data-product-id="{{ product.id }}">{{ product.name }}<br><b>{{ product.price }}</b></button>{% endfor %}
        </div>
    </div>
    <div class="col-sm-4 col-lg-3 delete-container" id="delete-area" style="display: none;">
        <i class="glyphicon glyphicon-trash"></i>
    </div>
    <div id="hidden-area" style="display: none;"></div>
    <div class="modal fade" id="menuItemEditModal" tabindex="-1" role="dialog" aria-labelledby="menuItemEditModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="menuItemModalLabel">Optionen</h4>
                </div>
                <div class="modal-body">
                    <label for="select-color">Farbe</label>
                    <select class="form-control" id="select-color">
                        <option value="danger">Rot</option>
                        <option value="warning">Gelb</option>
                        <option value="info">Hellblau</option>
                        <option value="primary">Blau</option>
                        <option value="success">Grün</option>
                        <option value="black">Schwarz</option>
                        <option value="default">Farblos</option>
                    </select>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Schließen</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="menu{{ menu.id }}_delete_modal" tabindex="-1" role="dialog" aria-labelledby="menu{{ product.id }}_delete_model_label">
            <form action="{% url 'kasse:delete_menu' menu.id %}" method="post">
                {% csrf_token %}
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="menu{{ menu.id }}_delete_model_label">Menü entfernen</h4>
                        </div>
                        <div class="modal-body">
                            Soll das Menü "{{ menu.name }}" wirklich entfernt werden?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Abbrechen</button>
                            <button type="submit" class="btn btn-danger">Entfernen</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    <script>
    var selected_element = null;

    function insertAtIndex(i, element) {
        if(i === 0) {
         $("#menu-container").prepend($(element));
         return;
        }


        $("#menu-container > .menu-item:nth-child(" + (i) + ")").after($(element));
    }

    function save() {
        var menu_data = [];
        $('#menu-container').find('.menu-item').each(function () {
            var index = $('.menu-item').index($(this));
            menu_data.push({
                sort: parseInt(index),
                color: $(this).attr('data-color'),
                menu_id: $(this).attr('data-product-id')
            });
        });
        $.post("{% url 'kasse:ajax_update_menu' menu.id %}", {data: JSON.stringify(menu_data)}, function(data) {
            $('#saved-alert').show();
            setTimeout(function () {
               $('#saved-alert').hide()
            }, 3000)
        })
    }

    function menu_item_onclick() {
        selected_element = $(this);
        load_setting_area();
        $('#menuItemEditModal').modal('show')
    }

    function load_setting_area() {
        $('#select-color').val(selected_element.attr('data-color'))
    }

    $('#select-color').on('change', function () {
        $(selected_element).removeClass('btn-'+selected_element.attr('data-color'));
        $(selected_element).addClass('btn-'+$(this).val());
        $(selected_element).attr('data-color', $(this).val())
    });

    var palette_product_draggable_options = {
        revert: function () {
            return !$(this).hasClass('dropped');
        },
        revertDuration: 200,
        cancel: false,
        appendTo: 'body',
        containment: 'body',
        scroll: true,
        helper: 'clone',
        start: function () {
            $('#add-button').show();
        },
        stop: function () {
            $('#menu-container').append($('#add-button').hide());
            $(this).removeClass('dropped')
        }
    };

    $(function () {
        $('#product-search-field').on('keyup', function () {
            $.getJSON('{% url 'kasse:search_products' %}', {'q': $(this).val()}, function(data){
                // git ToDo rebuild product list
                var results_container = $('#product-search-results');
                results_container.text('');
                for (var i in data) {
                    if (data.hasOwnProperty(i)) {
                        var product = data[i];
                        var product_element = $('<button class="btn btn-default btn-menu palette-product" data-product-id="'+product.id+'">'+product.name+'<br><b>'+product.price+'</b></button>');
                        product_element.draggable(palette_product_draggable_options);
                        results_container.append(product_element);
                    }
                }
            });
        });

        var current_drag_element_index = null;
        $('.palette-product').draggable(palette_product_draggable_options);
        var menu_item_draggable_options = {
            revert: function (e) {
                return !$(this).hasClass('dropped') && $(e).attr('id') !== 'delete-area';
            },
            revertDuration: 200,
            cancel: false,
            appendTo: 'body',
            containment: 'body',
            scroll: true,
            helper: 'clone',
            start: function () {
                $('#add-button').show();
                $('.products-container').hide();
                $('#delete-area').show();
                current_drag_element_index = $('#menu-container').find('.menu-item').index($(this));
                $('#hidden-area').append($(this));
                $(this).hide();
            },
            stop: function (e,u) {
                if ($(this).hasClass('dropped') || $(this).hasClass('removed')) {
                    $(this).removeClass('dropped removed')
                } else {
                    $(this).show();
                    insertAtIndex(current_drag_element_index, $(this));
                }
                $('#menu-container').append($('#add-button').hide());
                $('.products-container').show();
                $('#delete-area').hide();
            }
        };
        var menu_item_droppable_options = {
            over: function () {
                $('#add-button').insertBefore($(this));
            }
        };
        $('.menu-item').draggable(menu_item_draggable_options).droppable(menu_item_droppable_options).on('click', menu_item_onclick);
        $('#add-button').droppable({
            drop: function (event, ui) {
                var item_to_drop = $(ui.draggable);
                if(item_to_drop.hasClass('palette-product')) {
                    item_to_drop.addClass('dropped menu-item');
                    item_to_drop = item_to_drop.clone().draggable(menu_item_draggable_options).droppable(menu_item_droppable_options).on('click', menu_item_onclick);
                    item_to_drop.attr('data-color', 'default');
                }
                item_to_drop.insertBefore($(this)).show().addClass('dropped');
            },
            over: function () {
                $('#menu-container').append($(this));
                $('#add-button').insertBefore($(this));
            }
        });
        $('#delete-area').droppable({
            drop: function (event, ui) {
                $(ui.draggable).addClass('removed');
                $(ui.draggable).remove();
            },
            over: function () {
                $(this).addClass('dragover');
            },
            out: function () {
                $(this).removeClass('dragover');
            }
        });
    });
    </script>

{% endblock %}

templates/settings/product_form.html
{% extends 'settings/base.html' %}

{% block settings_content %}
    <h1>Produkt {% if edit %}bearbeiten{% else %}erstellen{% endif %}</h1>
    <br>
    <form action="{{ request.path }}" method="post" class="form-horizontal">
        {% include 'form.html' with form=form %}
        <button class="btn btn-primary">Speichern</button>
    </form>
{% endblock %}

templates/settings/product_list.html
{% extends 'settings/base.html' %}
{% load l10n %}

{% block settings_content %}
    <h1>Produkte</h1>
    <a href="{% url 'kasse:add_product' %}"><button class="btn btn-primary">Produkt erstellen</button></a>
    <table class="table table-striped table-hover">
    <thead>
    <tr>
        <th>Name</th>
        <th>Preis</th>
        <th>Kategorie</th>
        <th style="text-align: right;">Aktionen</th>
    </tr>
    </thead>
    <tbody>
    {% for product in products %}
    <tr>
    <td>{{ product.name }}</td>
    <td>{{ product.price|localize }}</td>
    <td>
        {% if product.category %}
            {{ product.category.name }}
        {% else %}
            Unkategorisiert
        {% endif %}
    </td>
    <td style="text-align: right;">
        <a href="{% url 'kasse:edit_product' product.id %}"><button class="btn btn-default btn-xs"><i class="glyphicon glyphicon-edit"></i></button></a>
        <a href="#" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#product{{ product.id }}_delete_modal"><i class="glyphicon glyphicon-trash"></i></a>
        <div class="modal fade" id="product{{ product.id }}_delete_modal" tabindex="-1" role="dialog" aria-labelledby="product{{ product.id }}_delete_model_label" style="text-align: left;">
            <form action="{% url 'kasse:delete_product' product.id %}" method="post">
                {% csrf_token %}
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="product{{ product.id }}_delete_model_label">Produkt löschen</h4>
                        </div>
                        <div class="modal-body">
                            Soll das Produkt "{{ product.name }} ({{ product.price }})" wirklich gelöscht werden?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Abbrechen</button>
                            <button type="submit" class="btn btn-danger">Löschen</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </td>
    </tr>
    {% endfor %}
    {% if not products %}
        <tr><td colspan="100" style="text-align: center;">
            Keine Produkte vorhanden.
        </td></tr>
    {% endif %}
    </tbody>
    </table>
    <h1>Kategorien</h1>
    <a href="{% url 'kasse:add_product_category' %}" class="btn btn-primary">Produktkategorie erstellen</a>
    <table class="table table-hover table-striped">
    <thead>
    <tr>
        <th>Name</th>
        <th style="text-align: right">Aktionen</th>
    </tr>
    </thead>
    <tbody>
    {% for category in product_categories %}
        <tr>
            <td>{{ category.name }}</td>
            <td style="text-align: right;">
                <a href="{% url 'kasse:edit_product_category' category.id %}" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-edit"></span></a>
                <button class="btn btn-danger btn-xs" data-toggle="modal" data-target="#category{{ category.id }}_delete_modal"><span class="glyphicon glyphicon-trash"></span></button>
                <div class="modal fade" id="category{{ category.id }}_delete_modal" tabindex="-1" role="dialog" aria-labelledby="category{{ category.id }}_delete_model_label" style="text-align: left;">
                    <form action="{% url 'kasse:remove_product_category' category.id %}" method="post">
                        {% csrf_token %}
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="category{{ category.id }}_delete_model_label">Produktkategorie löschen</h4>
                                </div>
                                <div class="modal-body">
                                    Soll die Produktkategorie "{{ category.name }}" wirklich gelöscht werden?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Abbrechen</button>
                                    <button type="submit" class="btn btn-danger">Löschen</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </td>
        </tr>
    {% endfor %}
    {% if not product_categories %}
        <tr><td colspan="100" style="text-align: center">
            Keine Produktkategorien vorhanden
        </td></tr>
    {% endif %}
    </tbody>
    </table>
{% endblock %}

templates/settings/table_set_form.html
{% extends 'settings/base.html' %}

{% block settings_content %}
    <h1>Tischanordnung {% if edit %}bearbeiten{% else %}erstellen{% endif %}</h1>
    <br>
    <form action="{{ request.path }}" method="post" class="form-horizontal">
        {% include 'form.html' with form=form %}
        <button class="btn btn-primary">Speichern</button>
    </form>
{% endblock %}

templates/settings/users.html
{% extends 'settings/base.html' %}

{% block settings_content %}
    <h1>Benutzer</h1>
    <a href="{% url 'kasse:add_user' %}" class="btn btn-primary">Benutzer anlegen</a>
    <table class="table table-striped table-hover">
    <thead>
    <tr>
        <th>Nutzername</th>
        <th style="text-align: right;">Aktionen</th>
    </tr>
    </thead>
    <tbody>
    {% for user in users %}
        <tr>
        <td>{{ user.username }}</td>
        <td style="text-align: right;">
            <a href="{% url 'kasse:set_password' user.id %}" class="btn btn-default btn-xs"><i class="fas fa-key"></i></a>
            <a href="#" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#user{{ user.id }}_delete_modal"><i class="glyphicon glyphicon-trash"></i></a>
            <div class="modal fade" id="user{{ user.id }}_delete_modal" tabindex="-1" role="dialog" aria-labelledby="user{{ user.id }}_delete_model_label">
            <form action="{% url 'kasse:remove_user' user.id %}" method="post">
                {% csrf_token %}
                <div class="modal-dialog" role="document" style="text-align: left;">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="user{{ user.id }}_delete_model_label">Benutzer löschen</h4>
                        </div>
                        <div class="modal-body">
                            Soll der Benutzer "{{ user.username }}" wirklich gelöscht werden?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Abbrechen</button>
                            <button type="submit" class="btn btn-danger">Löschen</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}