kasse/urls.py
from django.urls import path
from .views import *
from . import ajax_views

urlpatterns = [
    path('', kasse_view, name="kasse"),
    path('<int:menu_id>', menu_view, name='single_menu'),

    path('tableset/<int:table_set_id>', tableset_view, name="tableset"),
    path('tableset/<int:table_set_id>/<int:table_id>', table_menu_view, name="table_menu"),
    path('tableset/<int:table_set_id>/<int:table_id>/addProduct', add_product_to_table_view, name="add_product_to_table"),
    path('tableset/<int:table_set_id>/<int:table_id>/removeProduct', remove_product_from_table_view, name='remove_product_from_table'),
    path('tableset/<int:table_set_id>/<int:table_id>/book', book_table_view, name='book_table'),

    path('settings', settings_view, name="settings"),
    path('settings/<int:menu_id>', menu_edit_view, name="edit_menu"),
    path('settings/<int:menu_id>/delete', menu_delete_view, name="delete_menu"),

    path('settings/menus/add', add_menu_view, name="add_menu"),

    path('settings/table_sets/<int:table_set_id>', table_set_edit_view, name="edit_table_set"),
    path('settings/table_sets/<int:table_set_id>/edit', table_set_data_edit_view, name="edit_table_set_data"),
    path('settings/table_sets/<int:table_set_id>/delete', table_set_delete_view, name="delete_table_set"),
    path('settings/table_sets/add', add_table_set_view, name="add_table_set"),

    path('settings/products', product_list_view, name="product_list"),
    path('settings/products/add', add_product_view, name="add_product"),
    path('settings/products/<int:product_id>/edit', edit_product_view, name="edit_product"),
    path('settings/products/<int:product_id>/delete', remove_product, name="delete_product"),

    path('settings/productCategories/add', add_product_category_view, name="add_product_category"),
    path('settings/productCategories/<int:product_category_id>/edit', edit_product_category_view, name="edit_product_category"),
    path('settings/productCategories/<int:product_category_id>/remove', delete_product_category_view, name="remove_product_category"),

    path('settings/events', events_view, name="events"),
    path('settings/events/create', create_event_view, name="create_event"),
    path('settings/events/<int:event_id>', event_view, name="event"),
    path('settings/events/<int:event_id>/edit', edit_event_view, name="edit_event"),
    path('settings/events/<int:event_id>/remove', delete_event_view, name="remove_event"),
    path('settings/events/<int:event_id>/stats', event_stats_view, name="event_stats"),

    path('settings/users', users_view, name="users"),
    path('settings/users/create', add_user_view, name="add_user"),
    path('settings/users/<int:user_id>/set_password', set_password_view, name="set_password"),
    path('settings/users/<int:user_id>/remove', remove_user_view, name="remove_user"),

    path('settings/general_settings', general_settings_view, name="general_settings"),

    path('ajax/settings/menus/<int:menu_id>/remove_product', ajax_views.update_menu_view, name="ajax_update_menu"),
    path('ajax/settings/tablesets/<int:tableset_id>/update', ajax_views.update_tableset_view, name="ajax_update_tableset"),
    path('ajax/searchProducts', ajax_views.search_products, name="search_products"),
    path('ajax/add_sale', ajax_views.add_sale_view, name="add_sale"),
    path('ajax/open_drawer', ajax_views.open_drawer, name="open_drawer"),
    path('ajax/time', ajax_views.time_view, name="time"),

]

kassensystem/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from kasse import urls as kasse_urls

urlpatterns = [
    path('login', auth_views.LoginView.as_view(), name="login"),
    path('logout', auth_views.LogoutView.as_view(), name="logout"),
    path('', include(('kasse.urls', 'kasse'), namespace='kasse'))
]

kasse/models.py
from django.db import models
from djmoney.models.fields import MoneyField
import json

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField('Name', max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField('Name', max_length=50)
    category = models.ForeignKey(to=ProductCategory, on_delete=models.SET_DEFAULT, related_name='products',
                                 blank=True, default=None, null=True)
    price = MoneyField('Preis', decimal_places=2, max_digits=20, default_currency='EUR')


class Menu(models.Model):
    name = models.CharField('Name', max_length=50)
    products = models.ManyToManyField(Product, through='MenuItem')

    def sort_products(self):
        return self.products.order_by('menuitem__sort')

    def __str__(self):
        return self.name


class MenuItem(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    sort = models.IntegerField()
    color = models.CharField(max_length=50, default='default')


class AccountEntry(models.Model):
    types = (
        ('sale', 'Verkauf'),
        ('output', 'Entnahme'),
        ('input', 'Einzahlung')
    )
    type = models.CharField('Typ', choices=types, max_length=20)
    comment = models.TextField('Kommentar')
    amount = MoneyField('Betrag', max_digits=20, decimal_places=2, default_currency='EUR')
    timestamp = models.DateTimeField(auto_now=True)
    user = models.CharField('Benutzer', max_length=200, default='')


class Event(models.Model):
    name = models.CharField('Name', max_length=300)
    start = models.DateTimeField('Start')
    end = models.DateTimeField('Ende')


class TableSet(models.Model):
    name = models.CharField('Name', max_length=300)
    menu = models.ForeignKey(Menu, on_delete=models.PROTECT, verbose_name='Menü')


class Table(models.Model):
    name = models.CharField('Name', max_length=300)
    table_set = models.ForeignKey(TableSet, on_delete=models.CASCADE)
    pos_x = models.FloatField()
    pos_y = models.FloatField()
    size_x = models.FloatField()
    size_y = models.FloatField()
    bookings = models.TextField(blank=True)

    def total(self):
        total = 0.0
        if self.bookings != "":
            bookings = json.loads(self.bookings)
            for booking in bookings:
                total += booking.get('price', 0.0)
        return total

kasse/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from . import forms
from . import models
from django.contrib.auth import models as auth_models
import json
from datetime import timedelta
from django.conf import settings
import netifaces
from kasse.lib import worker_com
import debinterface


@login_required
def kasse_view(request):
    menus = models.Menu.objects.all()
    tablesets = models.TableSet.objects.all()
    return render(request, 'kasse.html', context={'title': 'Kasse',
                                                  'menus': menus,
                                                  'tablesets': tablesets})


@login_required
def menu_view(request, menu_id):
    try:
        menu = models.Menu.objects.get(id=menu_id)
        return render(request, 'menu.html', context={'title': 'Kasse {}'.format(menu.name),
                                                     'menu': menu,
                                                     'gpio_available': settings.GPIO_AVAILABLE})
    except models.Menu.DoesNotExist:
        return redirect('kasse:kasse')


@login_required
def tableset_view(request, table_set_id):
    try:
        tableset = models.TableSet.objects.get(id=table_set_id)
        return render(request, 'tableset.html', context={'title': 'Tischanordnung {}'.format(tableset.name),
                                                         'tableset': tableset})
    except models.TableSet.DoesNotExist:
        return redirect('kasse:kasse')


@login_required
def table_menu_view(request, table_set_id, table_id):
    try:
        tableset = models.TableSet.objects.get(id=table_set_id)
        table = tableset.table_set.get(id=table_id)
        menu = tableset.menu

        if table.bookings != '':
            bookings = json.loads(table.bookings)
        else:
            bookings = []

        total = 0.0
        for booking in bookings:
            total += booking.get('price', 0.0)

        categories = {}
        for category in models.ProductCategory.objects.filter(products__menu=menu):
            products = category.products.filter(menu=menu)
            categories[category.name] = products
        uncategorized = menu.products.filter(category__isnull=True)

        return render(request, 'table_menu.html', context={'title': 'Tisch {}'.format(table.name),
                                                           'table': table,
                                                           'bookings': bookings,
                                                           'total': total,
                                                           'categories': categories,
                                                           'uncategorized': uncategorized,
                                                           'menu': menu})
    except models.TableSet.DoesNotExist:
        return redirect('kasse:kasse')
    except models.Table.DoesNotExist:
        return redirect('kasse:tableset', table_set_id=table_set_id)


@login_required
def add_product_to_table_view(request, table_set_id, table_id):
    try:
        tableset = models.TableSet.objects.get(id=table_set_id)
        table = tableset.table_set.get(id=table_id)
        product = models.Product.objects.get(id=request.GET.get('productId', default=None))
        if table.bookings != '':
            bookings = json.loads(table.bookings)
        else:
            bookings = []
        bookings.append({'name': product.name, 'price': float(product.price.amount)})
        table.bookings = json.dumps(bookings)
        table.save()
    except models.TableSet.DoesNotExist:
        return redirect('kasse:kasse')
    except models.Table.DoesNotExist:
        return redirect('kasse:tableset', table_set_id=table_set_id)
    except models.Product.DoesNotExist:
        pass
    return redirect('kasse:table_menu', table_set_id=table_set_id, table_id=table_id)


@login_required
def remove_product_from_table_view(request, table_set_id, table_id):
    try:
        tableset = models.TableSet.objects.get(id=table_set_id)
        table = tableset.table_set.get(id=table_id)
        index = int(request.GET.get('index', default=None))
        all = int(request.GET.get('all', default=False))
        if index is not None and table.bookings != '':
            bookings = json.loads(table.bookings)
            bookings.pop(index)
            table.bookings = json.dumps(bookings)
            table.save()
        if all:
            table.bookings = ""
            table.save()
        return redirect('kasse:table_menu', table_set_id=table_set_id, table_id=table_id)
    except models.TableSet.DoesNotExist:
        return redirect('kasse:kasse')
    except models.Table.DoesNotExist:
        return redirect('kasse:tableset', table_set_id=table_set_id)


@login_required
def book_table_view(request, table_set_id, table_id):
    try:
        tableset = models.TableSet.objects.get(id=table_set_id)
        table = tableset.table_set.get(id=table_id)
        account_entry = models.AccountEntry(type='sale',
                                            comment='billing:{}'.format(table.bookings),
                                            amount=table.total(),
                                            user=request.user)
        account_entry.save()
        table.bookings = ''
        table.save()
        return redirect('kasse:tableset', table_set_id=table_set_id)
    except models.TableSet.DoesNotExist:
        return redirect('kasse:kasse')
    except models.Table.DoesNotExist:
        return redirect('kasse:tableset', table_set_id=table_set_id)


@login_required
def settings_view(request):
    menus = models.Menu.objects.all()
    table_sets = models.TableSet.objects.all()
    return render(request, 'settings/checkout_list.html', context={'title': 'Einstellungen',
                                                                   'menus': menus,
                                                                   'table_sets': table_sets})


@login_required
def add_menu_view(request):
    if request.method == 'POST':
        form = forms.MenuForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('kasse:settings')
    else:
        form = forms.MenuForm()

    return render(request, 'settings/menu_form.html', context={'title': 'Menu erstellen',
                                                               'form': form})


@login_required
def add_table_set_view(request):
    if request.method == 'POST':
        form = forms.TableSetForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('kasse:settings')
    else:
        form = forms.TableSetForm()

    return render(request, 'settings/table_set_form.html', context={'title': 'Tischanordnung erstellen',
                                                                    'form': form})


@login_required
def product_list_view(request):
    products = models.Product.objects.all()
    product_categories = models.ProductCategory.objects.all()
    return render(request, 'settings/product_list.html', context={'title': 'Produkte',
                                                                  'products': products,
                                                                  'product_categories': product_categories})


@login_required
def add_product_view(request):
    if request.method == 'POST':
        form = forms.ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('kasse:product_list')
    else:
        form = forms.ProductForm()

    return render(request, 'settings/product_form.html', context={'title': 'Produkt erstellen',
                                                                  'form': form})


@login_required
def edit_product_view(request, product_id):
    try:
        product = models.Product.objects.get(id=product_id)
        if request.method == 'POST':
            form = forms.ProductForm(request.POST, instance=product)
            if form.is_valid():
                form.save()
                return redirect('kasse:product_list')
        else:
            form = forms.ProductForm(instance=product)
        return render(request, 'settings/product_form.html', context={'title': 'Produkt bearbeiten',
                                                                      'form': form})
    except models.Product.DoesNotExist:
        return redirect('kasse:product_list')


@login_required
def remove_product(request, product_id):
    try:
        if request.method == 'POST':
            product = models.Product.objects.get(id=product_id)
            product.delete()
    except models.Product.DoesNotExist:
        pass
    return redirect('kasse:product_list')


@login_required
def add_product_category_view(request):
    if request.method == 'POST':
        form = forms.ProductCategoryForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('kasse:product_list')
    else:
        form = forms.ProductCategoryForm()
    return render(request, 'settings/product_category_form.html', context={'title': 'Produktkategorie erstellen',
                                                                           'form': form})


@login_required
def edit_product_category_view(request, product_category_id):
    try:
        product_category = models.ProductCategory.objects.get(id=product_category_id)
        if request.method == 'POST':
            form = forms.ProductCategoryForm(instance=product_category, data=request.POST)
            if form.is_valid():
                form.save()
                return redirect('kasse:product_list')
        else:
            form = forms.ProductCategoryForm(instance=product_category)
        return render(request, 'settings/product_category_form.html', context={'title': 'Produktkategorie bearbeiten',

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content = "width = device-width, initial-scale = 1.0, minimum-scale = 1, maximum-scale = 1, user-scalable = no" />
    <meta name="apple-mobile-web-app-title" content="Kassensystem" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <title>{% if title %}{{ title }} - {% endif %}Kassensystem</title>
    <link type="text/css" rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'bower_components/fontawesome/web-fonts-with-css/css/fontawesome-all.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'bower_components/jquery-ui/themes/base/jquery-ui.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script type="application/javascript" src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script type="application/javascript" src="{% static 'bower_components/jquery-ui/jquery-ui.min.js' %}"></script>
    <script type="application/javascript" src="{% static 'bower_components/jqueryui-touch-punch/jquery.ui.touch-punch.min.js' %}"></script>
    <script type="application/javascript" src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script type="application/javascript" src="{% static 'bower_components/moment/min/moment-with-locales.min.js' %}"></script>
    <script type="application/javascript" src="{% static 'bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %}"></script>
    <script type="application/javascript" src="{% static 'bower_components/chart.js/dist/Chart.min.js' %}"></script>
    <script type="application/javascript" src="{% static 'bower_components/pure-uuid/uuid.js' %}"></script>
    <script type="application/javascript">
        $(function () {
        var timeDiff = 0;
            $.get('{% url 'kasse:time' %}')
                .done(function (data) {
                    data = parseInt(data);
                    timeDiff = Math.floor(new Date().getTime() / 1000) - data;
                });
            function printTime () {
                var now = moment.unix(Math.floor(new Date().getTime() / 1000) - timeDiff);
                //$(this).text(now.format(format));
                $('[data-content="time"]').each(function (item) {
                    $(this).text(now.format(this.dataset.format))
                });
            }
            setInterval(printTime, 1000)
        });
    </script>
</head>
<body>
{% block body %}{% endblock %}
</body>
</html>

templates/form.html
{% csrf_token %}
{{ form.non_field_errors }}
{% for field in form %}
    <div class="form-group {% if field.errors %}has-feedback has-error{% endif %}">
        <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
        <div class="col-sm-10">
            {{ field }}
            {{ field.errors }}
        </div>
    </div>
{% endfor %}

templates/inside.html
{% extends 'base.html' %}

{% block body %}
{% endblock %}

templates/kasse.html
{% extends 'settings/base.html' %}

{% block settings_content %}
    <div class="container-fluid">
        {% for menu in menus %}<a href="{% url 'kasse:single_menu' menu.id %}" class="hidden-xs"><button class="btn btn-default btn-menu">{{ menu.name }}</button></a>{% endfor %}
        <br class="hidden-xs">
        <hr class="hidden-xs"/>
        <h4>Tischanordnungen</h4>
        {% for tableset in tablesets %}<a href="{% url 'kasse:tableset' tableset.id %}"><button class="btn btn-default btn-menu">{{ tableset.name }}</button></a>{% endfor %}
    </div>

{% endblock %}

templates/menu.html
{% extends 'base.html' %}
{% load l10n %}
{% load formats %}

{% block body %}
    <div class="container-fluid container-kasse">
        <div id="menu-container" class="col-sm-8 col-lg-9" style="min-height: 100vh;">
            {% for menuitem in menu.menuitem_set.all %}<button class="btn btn-{{ menuitem.color }} btn-menu menu-item" data-product-id="{{ menuitem.product.id }}" data-color="{{ menuitem.color }}" data-name="{{ menuitem.product.name }}" data-price="{{ menuitem.product.price|float|unlocalize }}">{{ menuitem.product.name }}<br><b class="price-nice">{{ menuitem.product.price }}</b></button>{% endfor %}
        </div>
        <div class="col-sm-4 col-lg-3" style="height: 100vh; max-height: 100vh; overflow-y: scroll;position: fixed; right: 0;">
            <div class="btn-group btn-group-justified" role="group">
                <div class="btn-group" role="group">
                    <button class="btn btn-danger btn-menu" onclick="clear_cart()">Abbrechen</button>
                </div>
                <div class="btn-group" role="group">
                    <button class="btn btn-success btn-menu" onclick="showFinalizeModal()">Bezahlen</button>
                </div>
            </div>
            <h3>Wahrenkorb</h3>
            <table class="table" id="cart">
                <thead>
                <tr>
                    <th>Produkt</th>
                    <th style="text-align: right;">Preis</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                </tbody>
                <tfoot>
                <tr>
                    <td style="border-top-width: 2px;"><b>Summe</b></td>
                    <td style="text-align: right; border-top-width: 2px;"><b id="sum-field">0,00 €</b></td>
                    <td style="border-top-width: 2px;"></td>
                </tr>
                </tfoot>
            </table>
            <a href="{% url 'kasse:kasse' %}"><button class="form-control btn btn-default btn-menu">Hauptmenü</button></a>
        </div>
    </div>
    <div class="modal fade" id="finalizeModal" tabindex="-1" role="dialog" aria-labelledby="finalizeModalLabel">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="finalizeModalLabel">Bezahlen</h4>
                </div>
                <div class="modal-body" style="min-height: 9.5cm;">
                    <table class="given-buttonfield" style="position: absolute;">
                        <tr>
                            <td><button class="btn btn-default btn-menu" onclick="givenConcat('7')">7</button></td>
                            <td><button class="btn btn-default btn-menu" onclick="givenConcat('8')">8</button></td>
                            <td><button class="btn btn-default btn-menu" onclick="givenConcat('9')">9</button></td>
                            <td rowspan="2"><button class="btn btn-danger btn-menu double-button rotate" onclick="abortModal()">Abbrechen</button></td>
                        </tr>
                        <tr>
                            <td><button class="btn btn-default btn-menu" onclick="givenConcat('4')">4</button></td>
                            <td><button class="btn btn-default btn-menu" onclick="givenConcat('5')">5</button></td>
                            <td><button class="btn btn-default btn-menu" onclick="givenConcat('6')">6</button></td>
                        </tr>
                        <tr>
                            <td><button class="btn btn-default btn-menu" onclick="givenConcat('1')">1</button></td>
                            <td><button class="btn btn-default btn-menu" onclick="givenConcat('2')">2</button></td>
                            <td><button class="btn btn-default btn-menu" onclick="givenConcat('3')">3</button></td>
                            <td rowspan="2">
                                {% if gpio_available %}
                                    <button class="btn btn-success btn-menu double-button rotate" onclick="openDrawer()">
                                        Kasse öffnen
                                    </button>
                                {% else %}
                                    <button class="btn btn-success btn-menu double-button rotate" onclick="finish()">
                                        Fertig
                                    </button>
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td><button class="btn btn-default btn-menu" onclick="givenConcat('0')">0</button></td>
                            <td colspan="2"><button class="btn btn-default btn-menu double-button" onclick="resetGiven()">Korrektur</button></td>
                        </tr>
                    </table>
                    <div id="finalizeCartTarget" style="margin-left: 9cm; height: 8cm; overflow-y: scroll;"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="alertModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-backdrop="static" style="z-index: 1051;">
    </div>
    <script>
    var opened = false;
    var aborted = false;
    function floatToNice(float) {
        return (float.toFixed(2)+' €').replace('.',',');
    }

    function abortModal() {
        aborted = true;
        $('#finalizeModal').modal('hide');
    }

    function getSum() {
        var table = $('#cart');
        var sum = 0;
        table.find('tbody').find('tr').each(function () {
            sum += parseFloat($(this).attr('data-price'));
        });
        return sum;
    }

    function recalculateSum() {
        var sum = getSum();
        $('#sum-field').text(floatToNice(sum));
    }

    function showFinalizeModal() {
        if ($('#cart').find('tbody').children().length == 0) {
            return;
        }
        $('#finalizeModal').modal('show');
        var cart = $('#cart').clone();
        cart.attr('id', 'cart-clone');
        cart.find('button').detach();
        cart.find('tfoot').append('<tr><td>Gegeben</td><td style="text-align: right;"><span id="givenField" data-given="0">0,00 €</span></td><td></td></tr>');
        cart.find('tfoot').append('<tr><td><b>Rückgeld</b></td><td style="text-align: right;"><b id="repeatField">0,00 €</b></td><td></td></tr>');
        var cartContainer = $('#finalizeCartTarget');
        cartContainer.text('');
        cartContainer.append(cart);
        setTimeout(function () {
            cartContainer.scrollTop(cart[0].scrollHeight);
        }, 200);
    }

    function clear_cart() {
        $('#cart').find('tbody').find('tr').remove();
        recalculateSum()
    }

    function givenConcat(number) {
        var givenField = $('#givenField');
        var givenString = givenField.attr('data-given');
        givenString = givenString+number;
        givenField.attr('data-given', givenString);
        var givenFloat = parseFloat(givenString)/100;
        var sumAmmount = getSum();
        givenField.text(floatToNice(givenFloat));
        $('#repeatField').text(floatToNice(givenFloat-sumAmmount));
    }

    function resetGiven() {
        var givenField = $('#givenField');
        givenField.attr('data-given', '0');
        givenField.text(floatToNice(0.0));
        $('#repeatField').text(floatToNice(0.0))
    }

    function deleteFromCart(event) {
        $(event.currentTarget).parent().parent().detach();
        recalculateSum();
    }

    function openDrawer() {
        if (getSum() === 0) {
            finish();
            return;
        }
        if (!opened){
            opened = true;
            $.post('{% url 'kasse:open_drawer' %}', {}, function(){
                if (!aborted) {
                    finish();
                } else {
                    aborted = false;
                }
                opened = false;
            })
        }
    }

    function finish() {
        var products = [];
        $('#cart').find('tbody').find('tr').each(function (e) {
            products.push({
                name: $(this).find('td').first().text(),
                price: parseFloat($(this).attr('data-price'))
            })
        });
        $.post('{% url 'kasse:add_sale' %}', {products: JSON.stringify(products)}, function (){
            window.location.reload()
        });
    }

    $('#menu-container').find('.menu-item').on('click', function () {
        var this_element = $(this);
        var name = this_element.attr('data-name');
        var price = parseFloat(this_element.attr('data-price'));
        var price_nice = this_element.find('.price-nice').text();
        var delete_from_cart_button = $('<button class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-minus"></i></button>');
        delete_from_cart_button.on('click', deleteFromCart);
        var table = $('#cart');
        var cart_row = $('<tr data-price="'+price+'"><td>'+name+'</td><td style="text-align: right;">'+price_nice+'</td><td class="action"></td></tr>');
        cart_row.find('.action').append(delete_from_cart_button);
        table.find('tbody').append(cart_row);
        recalculateSum();
    });
    $.ajaxSetup({
        error: function (x, status, error) {
            var self = this;
            var alertText = '';
            switch (this.url) {
                case '/ajax/add_sale':
                    alertText = 'Die Buchung konnte nicht abgeschlossen werden, da die Verbindung zur Kasse unterbrochen wurde.';
                    break;
                case '/ajax/open_drawer':
                    alertText = 'Die Kassenschublade konnte nicht geöffnet werden, da die Verbindung zur Kasse unterbrochen wurde.';
                    break;
                default:
                    alertText = 'Die Aktion konnte nicht ausgeführt werden, da die Verbindung zur Kasse unterbrochen wurde.';
                    break;
            }
            var alertModal = $('#alertModal');
            var alert = $('<div class="alert alert-danger" role="alert"></div>');
            alert.append('<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>');
            alert.append('<h4>Verbindung unterbrochen!</h4>');
            alert.append('<p>'+alertText+'</p>');
            alert.append('<br>');
            alert.append('<button class="btn btn-default" data-dismiss="modal">Schließen</button>');
            var retryButton = $('<button class="btn btn-default">Erneut versuchen</button>');
            retryButton.on('click', function () {
                alertModal.modal('hide');
                alertModal.on('hidden.bs.modal', function () {
                    alertModal.off('hidden.bs.modal');
                    $.ajax(self);
                });
            });
            alert.append(retryButton);
            alertModal.empty();
            alertModal.append(alert);
            alertModal.modal('show');
        }
    })
    </script>
{% endblock %}